package com.shashank.demo.dao;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.shashank.demo.entity.Category;

@Repository
public interface CategoryDao extends JpaRepository<Category, Integer>{
	//<Category,Integer> shows that its for Category class and primary attribute is integer
	//Autogenerated methods for save, findAll , findById, update, delete
	
	public Category findByName(String name);
	
	public List<Category>findByParentCat(int parentCat);
}
